import * as _17 from "./api/http";
import * as _18 from "./protobuf/any";
import * as _19 from "./protobuf/descriptor";
import * as _20 from "./protobuf/duration";
import * as _21 from "./protobuf/empty";
import * as _22 from "./protobuf/timestamp";
export declare namespace google {
    const api: {
        Http: {
            typeUrl: string;
            encode(message: _17.Http, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _17.Http;
            fromJSON(object: any): _17.Http;
            toJSON(message: _17.Http): unknown;
            fromPartial(object: Partial<_17.Http>): _17.Http;
            fromAmino(object: _17.HttpAmino): _17.Http;
            toAmino(message: _17.Http): _17.HttpAmino;
            fromAminoMsg(object: _17.HttpAminoMsg): _17.Http;
            fromProtoMsg(message: _17.HttpProtoMsg): _17.Http;
            toProto(message: _17.Http): Uint8Array;
            toProtoMsg(message: _17.Http): _17.HttpProtoMsg;
        };
        HttpRule: {
            typeUrl: string;
            encode(message: _17.HttpRule, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _17.HttpRule;
            fromJSON(object: any): _17.HttpRule;
            toJSON(message: _17.HttpRule): unknown;
            fromPartial(object: Partial<_17.HttpRule>): _17.HttpRule;
            fromAmino(object: _17.HttpRuleAmino): _17.HttpRule;
            toAmino(message: _17.HttpRule): _17.HttpRuleAmino;
            fromAminoMsg(object: _17.HttpRuleAminoMsg): _17.HttpRule;
            fromProtoMsg(message: _17.HttpRuleProtoMsg): _17.HttpRule;
            toProto(message: _17.HttpRule): Uint8Array;
            toProtoMsg(message: _17.HttpRule): _17.HttpRuleProtoMsg;
        };
        CustomHttpPattern: {
            typeUrl: string;
            encode(message: _17.CustomHttpPattern, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _17.CustomHttpPattern;
            fromJSON(object: any): _17.CustomHttpPattern;
            toJSON(message: _17.CustomHttpPattern): unknown;
            fromPartial(object: Partial<_17.CustomHttpPattern>): _17.CustomHttpPattern;
            fromAmino(object: _17.CustomHttpPatternAmino): _17.CustomHttpPattern;
            toAmino(message: _17.CustomHttpPattern): _17.CustomHttpPatternAmino;
            fromAminoMsg(object: _17.CustomHttpPatternAminoMsg): _17.CustomHttpPattern;
            fromProtoMsg(message: _17.CustomHttpPatternProtoMsg): _17.CustomHttpPattern;
            toProto(message: _17.CustomHttpPattern): Uint8Array;
            toProtoMsg(message: _17.CustomHttpPattern): _17.CustomHttpPatternProtoMsg;
        };
    };
    const protobuf: {
        Timestamp: {
            typeUrl: string;
            encode(message: _22.Timestamp, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _22.Timestamp;
            fromJSON(object: any): _22.Timestamp;
            toJSON(message: _22.Timestamp): unknown;
            fromPartial(object: Partial<_22.Timestamp>): _22.Timestamp;
            fromAmino(object: string): _22.Timestamp;
            toAmino(message: _22.Timestamp): string;
            fromAminoMsg(object: _22.TimestampAminoMsg): _22.Timestamp;
            fromProtoMsg(message: _22.TimestampProtoMsg): _22.Timestamp;
            toProto(message: _22.Timestamp): Uint8Array;
            toProtoMsg(message: _22.Timestamp): _22.TimestampProtoMsg;
        };
        Empty: {
            typeUrl: string;
            encode(_: _21.Empty, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _21.Empty;
            fromJSON(_: any): _21.Empty;
            toJSON(_: _21.Empty): unknown;
            fromPartial(_: Partial<_21.Empty>): _21.Empty;
            fromAmino(_: _21.EmptyAmino): _21.Empty;
            toAmino(_: _21.Empty): _21.EmptyAmino;
            fromAminoMsg(object: _21.EmptyAminoMsg): _21.Empty;
            fromProtoMsg(message: _21.EmptyProtoMsg): _21.Empty;
            toProto(message: _21.Empty): Uint8Array;
            toProtoMsg(message: _21.Empty): _21.EmptyProtoMsg;
        };
        Duration: {
            typeUrl: string;
            encode(message: _20.Duration, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _20.Duration;
            fromJSON(object: any): _20.Duration;
            toJSON(message: _20.Duration): unknown;
            fromPartial(object: Partial<_20.Duration>): _20.Duration;
            fromAmino(object: string): _20.Duration;
            toAmino(message: _20.Duration): string;
            fromAminoMsg(object: _20.DurationAminoMsg): _20.Duration;
            fromProtoMsg(message: _20.DurationProtoMsg): _20.Duration;
            toProto(message: _20.Duration): Uint8Array;
            toProtoMsg(message: _20.Duration): _20.DurationProtoMsg;
        };
        fieldDescriptorProto_TypeFromJSON(object: any): _19.FieldDescriptorProto_Type;
        fieldDescriptorProto_TypeToJSON(object: _19.FieldDescriptorProto_Type): string;
        fieldDescriptorProto_LabelFromJSON(object: any): _19.FieldDescriptorProto_Label;
        fieldDescriptorProto_LabelToJSON(object: _19.FieldDescriptorProto_Label): string;
        fileOptions_OptimizeModeFromJSON(object: any): _19.FileOptions_OptimizeMode;
        fileOptions_OptimizeModeToJSON(object: _19.FileOptions_OptimizeMode): string;
        fieldOptions_CTypeFromJSON(object: any): _19.FieldOptions_CType;
        fieldOptions_CTypeToJSON(object: _19.FieldOptions_CType): string;
        fieldOptions_JSTypeFromJSON(object: any): _19.FieldOptions_JSType;
        fieldOptions_JSTypeToJSON(object: _19.FieldOptions_JSType): string;
        methodOptions_IdempotencyLevelFromJSON(object: any): _19.MethodOptions_IdempotencyLevel;
        methodOptions_IdempotencyLevelToJSON(object: _19.MethodOptions_IdempotencyLevel): string;
        FieldDescriptorProto_Type: typeof _19.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeSDKType: typeof _19.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeAmino: typeof _19.FieldDescriptorProto_Type;
        FieldDescriptorProto_Label: typeof _19.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelSDKType: typeof _19.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelAmino: typeof _19.FieldDescriptorProto_Label;
        FileOptions_OptimizeMode: typeof _19.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeSDKType: typeof _19.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeAmino: typeof _19.FileOptions_OptimizeMode;
        FieldOptions_CType: typeof _19.FieldOptions_CType;
        FieldOptions_CTypeSDKType: typeof _19.FieldOptions_CType;
        FieldOptions_CTypeAmino: typeof _19.FieldOptions_CType;
        FieldOptions_JSType: typeof _19.FieldOptions_JSType;
        FieldOptions_JSTypeSDKType: typeof _19.FieldOptions_JSType;
        FieldOptions_JSTypeAmino: typeof _19.FieldOptions_JSType;
        MethodOptions_IdempotencyLevel: typeof _19.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelSDKType: typeof _19.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelAmino: typeof _19.MethodOptions_IdempotencyLevel;
        FileDescriptorSet: {
            typeUrl: string;
            encode(message: _19.FileDescriptorSet, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _19.FileDescriptorSet;
            fromJSON(object: any): _19.FileDescriptorSet;
            toJSON(message: _19.FileDescriptorSet): unknown;
            fromPartial(object: Partial<_19.FileDescriptorSet>): _19.FileDescriptorSet;
            fromAmino(object: _19.FileDescriptorSetAmino): _19.FileDescriptorSet;
            toAmino(message: _19.FileDescriptorSet): _19.FileDescriptorSetAmino;
            fromAminoMsg(object: _19.FileDescriptorSetAminoMsg): _19.FileDescriptorSet;
            fromProtoMsg(message: _19.FileDescriptorSetProtoMsg): _19.FileDescriptorSet;
            toProto(message: _19.FileDescriptorSet): Uint8Array;
            toProtoMsg(message: _19.FileDescriptorSet): _19.FileDescriptorSetProtoMsg;
        };
        FileDescriptorProto: {
            typeUrl: string;
            encode(message: _19.FileDescriptorProto, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _19.FileDescriptorProto;
            fromJSON(object: any): _19.FileDescriptorProto;
            toJSON(message: _19.FileDescriptorProto): unknown;
            fromPartial(object: Partial<_19.FileDescriptorProto>): _19.FileDescriptorProto;
            fromAmino(object: _19.FileDescriptorProtoAmino): _19.FileDescriptorProto;
            toAmino(message: _19.FileDescriptorProto): _19.FileDescriptorProtoAmino;
            fromAminoMsg(object: _19.FileDescriptorProtoAminoMsg): _19.FileDescriptorProto;
            fromProtoMsg(message: _19.FileDescriptorProtoProtoMsg): _19.FileDescriptorProto;
            toProto(message: _19.FileDescriptorProto): Uint8Array;
            toProtoMsg(message: _19.FileDescriptorProto): _19.FileDescriptorProtoProtoMsg;
        };
        DescriptorProto: {
            typeUrl: string;
            encode(message: _19.DescriptorProto, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _19.DescriptorProto;
            fromJSON(object: any): _19.DescriptorProto;
            toJSON(message: _19.DescriptorProto): unknown;
            fromPartial(object: Partial<_19.DescriptorProto>): _19.DescriptorProto;
            fromAmino(object: _19.DescriptorProtoAmino): _19.DescriptorProto;
            toAmino(message: _19.DescriptorProto): _19.DescriptorProtoAmino;
            fromAminoMsg(object: _19.DescriptorProtoAminoMsg): _19.DescriptorProto;
            fromProtoMsg(message: _19.DescriptorProtoProtoMsg): _19.DescriptorProto;
            toProto(message: _19.DescriptorProto): Uint8Array;
            toProtoMsg(message: _19.DescriptorProto): _19.DescriptorProtoProtoMsg;
        };
        DescriptorProto_ExtensionRange: {
            typeUrl: string;
            encode(message: _19.DescriptorProto_ExtensionRange, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _19.DescriptorProto_ExtensionRange;
            fromJSON(object: any): _19.DescriptorProto_ExtensionRange;
            toJSON(message: _19.DescriptorProto_ExtensionRange): unknown;
            fromPartial(object: Partial<_19.DescriptorProto_ExtensionRange>): _19.DescriptorProto_ExtensionRange;
            fromAmino(object: _19.DescriptorProto_ExtensionRangeAmino): _19.DescriptorProto_ExtensionRange;
            toAmino(message: _19.DescriptorProto_ExtensionRange): _19.DescriptorProto_ExtensionRangeAmino;
            fromAminoMsg(object: _19.DescriptorProto_ExtensionRangeAminoMsg): _19.DescriptorProto_ExtensionRange;
            fromProtoMsg(message: _19.DescriptorProto_ExtensionRangeProtoMsg): _19.DescriptorProto_ExtensionRange;
            toProto(message: _19.DescriptorProto_ExtensionRange): Uint8Array;
            toProtoMsg(message: _19.DescriptorProto_ExtensionRange): _19.DescriptorProto_ExtensionRangeProtoMsg;
        };
        DescriptorProto_ReservedRange: {
            typeUrl: string;
            encode(message: _19.DescriptorProto_ReservedRange, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _19.DescriptorProto_ReservedRange;
            fromJSON(object: any): _19.DescriptorProto_ReservedRange;
            toJSON(message: _19.DescriptorProto_ReservedRange): unknown;
            fromPartial(object: Partial<_19.DescriptorProto_ReservedRange>): _19.DescriptorProto_ReservedRange;
            fromAmino(object: _19.DescriptorProto_ReservedRangeAmino): _19.DescriptorProto_ReservedRange;
            toAmino(message: _19.DescriptorProto_ReservedRange): _19.DescriptorProto_ReservedRangeAmino;
            fromAminoMsg(object: _19.DescriptorProto_ReservedRangeAminoMsg): _19.DescriptorProto_ReservedRange;
            fromProtoMsg(message: _19.DescriptorProto_ReservedRangeProtoMsg): _19.DescriptorProto_ReservedRange;
            toProto(message: _19.DescriptorProto_ReservedRange): Uint8Array;
            toProtoMsg(message: _19.DescriptorProto_ReservedRange): _19.DescriptorProto_ReservedRangeProtoMsg;
        };
        ExtensionRangeOptions: {
            typeUrl: string;
            encode(message: _19.ExtensionRangeOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _19.ExtensionRangeOptions;
            fromJSON(object: any): _19.ExtensionRangeOptions;
            toJSON(message: _19.ExtensionRangeOptions): unknown;
            fromPartial(object: Partial<_19.ExtensionRangeOptions>): _19.ExtensionRangeOptions;
            fromAmino(object: _19.ExtensionRangeOptionsAmino): _19.ExtensionRangeOptions;
            toAmino(message: _19.ExtensionRangeOptions): _19.ExtensionRangeOptionsAmino;
            fromAminoMsg(object: _19.ExtensionRangeOptionsAminoMsg): _19.ExtensionRangeOptions;
            fromProtoMsg(message: _19.ExtensionRangeOptionsProtoMsg): _19.ExtensionRangeOptions;
            toProto(message: _19.ExtensionRangeOptions): Uint8Array;
            toProtoMsg(message: _19.ExtensionRangeOptions): _19.ExtensionRangeOptionsProtoMsg;
        };
        FieldDescriptorProto: {
            typeUrl: string;
            encode(message: _19.FieldDescriptorProto, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _19.FieldDescriptorProto;
            fromJSON(object: any): _19.FieldDescriptorProto;
            toJSON(message: _19.FieldDescriptorProto): unknown;
            fromPartial(object: Partial<_19.FieldDescriptorProto>): _19.FieldDescriptorProto;
            fromAmino(object: _19.FieldDescriptorProtoAmino): _19.FieldDescriptorProto;
            toAmino(message: _19.FieldDescriptorProto): _19.FieldDescriptorProtoAmino;
            fromAminoMsg(object: _19.FieldDescriptorProtoAminoMsg): _19.FieldDescriptorProto;
            fromProtoMsg(message: _19.FieldDescriptorProtoProtoMsg): _19.FieldDescriptorProto;
            toProto(message: _19.FieldDescriptorProto): Uint8Array;
            toProtoMsg(message: _19.FieldDescriptorProto): _19.FieldDescriptorProtoProtoMsg;
        };
        OneofDescriptorProto: {
            typeUrl: string;
            encode(message: _19.OneofDescriptorProto, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _19.OneofDescriptorProto;
            fromJSON(object: any): _19.OneofDescriptorProto;
            toJSON(message: _19.OneofDescriptorProto): unknown;
            fromPartial(object: Partial<_19.OneofDescriptorProto>): _19.OneofDescriptorProto;
            fromAmino(object: _19.OneofDescriptorProtoAmino): _19.OneofDescriptorProto;
            toAmino(message: _19.OneofDescriptorProto): _19.OneofDescriptorProtoAmino;
            fromAminoMsg(object: _19.OneofDescriptorProtoAminoMsg): _19.OneofDescriptorProto;
            fromProtoMsg(message: _19.OneofDescriptorProtoProtoMsg): _19.OneofDescriptorProto;
            toProto(message: _19.OneofDescriptorProto): Uint8Array;
            toProtoMsg(message: _19.OneofDescriptorProto): _19.OneofDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto: {
            typeUrl: string;
            encode(message: _19.EnumDescriptorProto, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _19.EnumDescriptorProto;
            fromJSON(object: any): _19.EnumDescriptorProto;
            toJSON(message: _19.EnumDescriptorProto): unknown;
            fromPartial(object: Partial<_19.EnumDescriptorProto>): _19.EnumDescriptorProto;
            fromAmino(object: _19.EnumDescriptorProtoAmino): _19.EnumDescriptorProto;
            toAmino(message: _19.EnumDescriptorProto): _19.EnumDescriptorProtoAmino;
            fromAminoMsg(object: _19.EnumDescriptorProtoAminoMsg): _19.EnumDescriptorProto;
            fromProtoMsg(message: _19.EnumDescriptorProtoProtoMsg): _19.EnumDescriptorProto;
            toProto(message: _19.EnumDescriptorProto): Uint8Array;
            toProtoMsg(message: _19.EnumDescriptorProto): _19.EnumDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto_EnumReservedRange: {
            typeUrl: string;
            encode(message: _19.EnumDescriptorProto_EnumReservedRange, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _19.EnumDescriptorProto_EnumReservedRange;
            fromJSON(object: any): _19.EnumDescriptorProto_EnumReservedRange;
            toJSON(message: _19.EnumDescriptorProto_EnumReservedRange): unknown;
            fromPartial(object: Partial<_19.EnumDescriptorProto_EnumReservedRange>): _19.EnumDescriptorProto_EnumReservedRange;
            fromAmino(object: _19.EnumDescriptorProto_EnumReservedRangeAmino): _19.EnumDescriptorProto_EnumReservedRange;
            toAmino(message: _19.EnumDescriptorProto_EnumReservedRange): _19.EnumDescriptorProto_EnumReservedRangeAmino;
            fromAminoMsg(object: _19.EnumDescriptorProto_EnumReservedRangeAminoMsg): _19.EnumDescriptorProto_EnumReservedRange;
            fromProtoMsg(message: _19.EnumDescriptorProto_EnumReservedRangeProtoMsg): _19.EnumDescriptorProto_EnumReservedRange;
            toProto(message: _19.EnumDescriptorProto_EnumReservedRange): Uint8Array;
            toProtoMsg(message: _19.EnumDescriptorProto_EnumReservedRange): _19.EnumDescriptorProto_EnumReservedRangeProtoMsg;
        };
        EnumValueDescriptorProto: {
            typeUrl: string;
            encode(message: _19.EnumValueDescriptorProto, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _19.EnumValueDescriptorProto;
            fromJSON(object: any): _19.EnumValueDescriptorProto;
            toJSON(message: _19.EnumValueDescriptorProto): unknown;
            fromPartial(object: Partial<_19.EnumValueDescriptorProto>): _19.EnumValueDescriptorProto;
            fromAmino(object: _19.EnumValueDescriptorProtoAmino): _19.EnumValueDescriptorProto;
            toAmino(message: _19.EnumValueDescriptorProto): _19.EnumValueDescriptorProtoAmino;
            fromAminoMsg(object: _19.EnumValueDescriptorProtoAminoMsg): _19.EnumValueDescriptorProto;
            fromProtoMsg(message: _19.EnumValueDescriptorProtoProtoMsg): _19.EnumValueDescriptorProto;
            toProto(message: _19.EnumValueDescriptorProto): Uint8Array;
            toProtoMsg(message: _19.EnumValueDescriptorProto): _19.EnumValueDescriptorProtoProtoMsg;
        };
        ServiceDescriptorProto: {
            typeUrl: string;
            encode(message: _19.ServiceDescriptorProto, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _19.ServiceDescriptorProto;
            fromJSON(object: any): _19.ServiceDescriptorProto;
            toJSON(message: _19.ServiceDescriptorProto): unknown;
            fromPartial(object: Partial<_19.ServiceDescriptorProto>): _19.ServiceDescriptorProto;
            fromAmino(object: _19.ServiceDescriptorProtoAmino): _19.ServiceDescriptorProto;
            toAmino(message: _19.ServiceDescriptorProto): _19.ServiceDescriptorProtoAmino;
            fromAminoMsg(object: _19.ServiceDescriptorProtoAminoMsg): _19.ServiceDescriptorProto;
            fromProtoMsg(message: _19.ServiceDescriptorProtoProtoMsg): _19.ServiceDescriptorProto;
            toProto(message: _19.ServiceDescriptorProto): Uint8Array;
            toProtoMsg(message: _19.ServiceDescriptorProto): _19.ServiceDescriptorProtoProtoMsg;
        };
        MethodDescriptorProto: {
            typeUrl: string;
            encode(message: _19.MethodDescriptorProto, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _19.MethodDescriptorProto;
            fromJSON(object: any): _19.MethodDescriptorProto;
            toJSON(message: _19.MethodDescriptorProto): unknown;
            fromPartial(object: Partial<_19.MethodDescriptorProto>): _19.MethodDescriptorProto;
            fromAmino(object: _19.MethodDescriptorProtoAmino): _19.MethodDescriptorProto;
            toAmino(message: _19.MethodDescriptorProto): _19.MethodDescriptorProtoAmino;
            fromAminoMsg(object: _19.MethodDescriptorProtoAminoMsg): _19.MethodDescriptorProto;
            fromProtoMsg(message: _19.MethodDescriptorProtoProtoMsg): _19.MethodDescriptorProto;
            toProto(message: _19.MethodDescriptorProto): Uint8Array;
            toProtoMsg(message: _19.MethodDescriptorProto): _19.MethodDescriptorProtoProtoMsg;
        };
        FileOptions: {
            typeUrl: string;
            encode(message: _19.FileOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _19.FileOptions;
            fromJSON(object: any): _19.FileOptions;
            toJSON(message: _19.FileOptions): unknown;
            fromPartial(object: Partial<_19.FileOptions>): _19.FileOptions;
            fromAmino(object: _19.FileOptionsAmino): _19.FileOptions;
            toAmino(message: _19.FileOptions): _19.FileOptionsAmino;
            fromAminoMsg(object: _19.FileOptionsAminoMsg): _19.FileOptions;
            fromProtoMsg(message: _19.FileOptionsProtoMsg): _19.FileOptions;
            toProto(message: _19.FileOptions): Uint8Array;
            toProtoMsg(message: _19.FileOptions): _19.FileOptionsProtoMsg;
        };
        MessageOptions: {
            typeUrl: string;
            encode(message: _19.MessageOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _19.MessageOptions;
            fromJSON(object: any): _19.MessageOptions;
            toJSON(message: _19.MessageOptions): unknown;
            fromPartial(object: Partial<_19.MessageOptions>): _19.MessageOptions;
            fromAmino(object: _19.MessageOptionsAmino): _19.MessageOptions;
            toAmino(message: _19.MessageOptions): _19.MessageOptionsAmino;
            fromAminoMsg(object: _19.MessageOptionsAminoMsg): _19.MessageOptions;
            fromProtoMsg(message: _19.MessageOptionsProtoMsg): _19.MessageOptions;
            toProto(message: _19.MessageOptions): Uint8Array;
            toProtoMsg(message: _19.MessageOptions): _19.MessageOptionsProtoMsg;
        };
        FieldOptions: {
            typeUrl: string;
            encode(message: _19.FieldOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _19.FieldOptions;
            fromJSON(object: any): _19.FieldOptions;
            toJSON(message: _19.FieldOptions): unknown;
            fromPartial(object: Partial<_19.FieldOptions>): _19.FieldOptions;
            fromAmino(object: _19.FieldOptionsAmino): _19.FieldOptions;
            toAmino(message: _19.FieldOptions): _19.FieldOptionsAmino;
            fromAminoMsg(object: _19.FieldOptionsAminoMsg): _19.FieldOptions;
            fromProtoMsg(message: _19.FieldOptionsProtoMsg): _19.FieldOptions;
            toProto(message: _19.FieldOptions): Uint8Array;
            toProtoMsg(message: _19.FieldOptions): _19.FieldOptionsProtoMsg;
        };
        OneofOptions: {
            typeUrl: string;
            encode(message: _19.OneofOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _19.OneofOptions;
            fromJSON(object: any): _19.OneofOptions;
            toJSON(message: _19.OneofOptions): unknown;
            fromPartial(object: Partial<_19.OneofOptions>): _19.OneofOptions;
            fromAmino(object: _19.OneofOptionsAmino): _19.OneofOptions;
            toAmino(message: _19.OneofOptions): _19.OneofOptionsAmino;
            fromAminoMsg(object: _19.OneofOptionsAminoMsg): _19.OneofOptions;
            fromProtoMsg(message: _19.OneofOptionsProtoMsg): _19.OneofOptions;
            toProto(message: _19.OneofOptions): Uint8Array;
            toProtoMsg(message: _19.OneofOptions): _19.OneofOptionsProtoMsg;
        };
        EnumOptions: {
            typeUrl: string;
            encode(message: _19.EnumOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _19.EnumOptions;
            fromJSON(object: any): _19.EnumOptions;
            toJSON(message: _19.EnumOptions): unknown;
            fromPartial(object: Partial<_19.EnumOptions>): _19.EnumOptions;
            fromAmino(object: _19.EnumOptionsAmino): _19.EnumOptions;
            toAmino(message: _19.EnumOptions): _19.EnumOptionsAmino;
            fromAminoMsg(object: _19.EnumOptionsAminoMsg): _19.EnumOptions;
            fromProtoMsg(message: _19.EnumOptionsProtoMsg): _19.EnumOptions;
            toProto(message: _19.EnumOptions): Uint8Array;
            toProtoMsg(message: _19.EnumOptions): _19.EnumOptionsProtoMsg;
        };
        EnumValueOptions: {
            typeUrl: string;
            encode(message: _19.EnumValueOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _19.EnumValueOptions;
            fromJSON(object: any): _19.EnumValueOptions;
            toJSON(message: _19.EnumValueOptions): unknown;
            fromPartial(object: Partial<_19.EnumValueOptions>): _19.EnumValueOptions;
            fromAmino(object: _19.EnumValueOptionsAmino): _19.EnumValueOptions;
            toAmino(message: _19.EnumValueOptions): _19.EnumValueOptionsAmino;
            fromAminoMsg(object: _19.EnumValueOptionsAminoMsg): _19.EnumValueOptions;
            fromProtoMsg(message: _19.EnumValueOptionsProtoMsg): _19.EnumValueOptions;
            toProto(message: _19.EnumValueOptions): Uint8Array;
            toProtoMsg(message: _19.EnumValueOptions): _19.EnumValueOptionsProtoMsg;
        };
        ServiceOptions: {
            typeUrl: string;
            encode(message: _19.ServiceOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _19.ServiceOptions;
            fromJSON(object: any): _19.ServiceOptions;
            toJSON(message: _19.ServiceOptions): unknown;
            fromPartial(object: Partial<_19.ServiceOptions>): _19.ServiceOptions;
            fromAmino(object: _19.ServiceOptionsAmino): _19.ServiceOptions;
            toAmino(message: _19.ServiceOptions): _19.ServiceOptionsAmino;
            fromAminoMsg(object: _19.ServiceOptionsAminoMsg): _19.ServiceOptions;
            fromProtoMsg(message: _19.ServiceOptionsProtoMsg): _19.ServiceOptions;
            toProto(message: _19.ServiceOptions): Uint8Array;
            toProtoMsg(message: _19.ServiceOptions): _19.ServiceOptionsProtoMsg;
        };
        MethodOptions: {
            typeUrl: string;
            encode(message: _19.MethodOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _19.MethodOptions;
            fromJSON(object: any): _19.MethodOptions;
            toJSON(message: _19.MethodOptions): unknown;
            fromPartial(object: Partial<_19.MethodOptions>): _19.MethodOptions;
            fromAmino(object: _19.MethodOptionsAmino): _19.MethodOptions;
            toAmino(message: _19.MethodOptions): _19.MethodOptionsAmino;
            fromAminoMsg(object: _19.MethodOptionsAminoMsg): _19.MethodOptions;
            fromProtoMsg(message: _19.MethodOptionsProtoMsg): _19.MethodOptions;
            toProto(message: _19.MethodOptions): Uint8Array;
            toProtoMsg(message: _19.MethodOptions): _19.MethodOptionsProtoMsg;
        };
        UninterpretedOption: {
            typeUrl: string;
            encode(message: _19.UninterpretedOption, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _19.UninterpretedOption;
            fromJSON(object: any): _19.UninterpretedOption;
            toJSON(message: _19.UninterpretedOption): unknown;
            fromPartial(object: Partial<_19.UninterpretedOption>): _19.UninterpretedOption;
            fromAmino(object: _19.UninterpretedOptionAmino): _19.UninterpretedOption;
            toAmino(message: _19.UninterpretedOption): _19.UninterpretedOptionAmino;
            fromAminoMsg(object: _19.UninterpretedOptionAminoMsg): _19.UninterpretedOption;
            fromProtoMsg(message: _19.UninterpretedOptionProtoMsg): _19.UninterpretedOption;
            toProto(message: _19.UninterpretedOption): Uint8Array;
            toProtoMsg(message: _19.UninterpretedOption): _19.UninterpretedOptionProtoMsg;
        };
        UninterpretedOption_NamePart: {
            typeUrl: string;
            encode(message: _19.UninterpretedOption_NamePart, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _19.UninterpretedOption_NamePart;
            fromJSON(object: any): _19.UninterpretedOption_NamePart;
            toJSON(message: _19.UninterpretedOption_NamePart): unknown;
            fromPartial(object: Partial<_19.UninterpretedOption_NamePart>): _19.UninterpretedOption_NamePart;
            fromAmino(object: _19.UninterpretedOption_NamePartAmino): _19.UninterpretedOption_NamePart;
            toAmino(message: _19.UninterpretedOption_NamePart): _19.UninterpretedOption_NamePartAmino;
            fromAminoMsg(object: _19.UninterpretedOption_NamePartAminoMsg): _19.UninterpretedOption_NamePart;
            fromProtoMsg(message: _19.UninterpretedOption_NamePartProtoMsg): _19.UninterpretedOption_NamePart;
            toProto(message: _19.UninterpretedOption_NamePart): Uint8Array;
            toProtoMsg(message: _19.UninterpretedOption_NamePart): _19.UninterpretedOption_NamePartProtoMsg;
        };
        SourceCodeInfo: {
            typeUrl: string;
            encode(message: _19.SourceCodeInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _19.SourceCodeInfo;
            fromJSON(object: any): _19.SourceCodeInfo;
            toJSON(message: _19.SourceCodeInfo): unknown;
            fromPartial(object: Partial<_19.SourceCodeInfo>): _19.SourceCodeInfo;
            fromAmino(object: _19.SourceCodeInfoAmino): _19.SourceCodeInfo;
            toAmino(message: _19.SourceCodeInfo): _19.SourceCodeInfoAmino;
            fromAminoMsg(object: _19.SourceCodeInfoAminoMsg): _19.SourceCodeInfo;
            fromProtoMsg(message: _19.SourceCodeInfoProtoMsg): _19.SourceCodeInfo;
            toProto(message: _19.SourceCodeInfo): Uint8Array;
            toProtoMsg(message: _19.SourceCodeInfo): _19.SourceCodeInfoProtoMsg;
        };
        SourceCodeInfo_Location: {
            typeUrl: string;
            encode(message: _19.SourceCodeInfo_Location, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _19.SourceCodeInfo_Location;
            fromJSON(object: any): _19.SourceCodeInfo_Location;
            toJSON(message: _19.SourceCodeInfo_Location): unknown;
            fromPartial(object: Partial<_19.SourceCodeInfo_Location>): _19.SourceCodeInfo_Location;
            fromAmino(object: _19.SourceCodeInfo_LocationAmino): _19.SourceCodeInfo_Location;
            toAmino(message: _19.SourceCodeInfo_Location): _19.SourceCodeInfo_LocationAmino;
            fromAminoMsg(object: _19.SourceCodeInfo_LocationAminoMsg): _19.SourceCodeInfo_Location;
            fromProtoMsg(message: _19.SourceCodeInfo_LocationProtoMsg): _19.SourceCodeInfo_Location;
            toProto(message: _19.SourceCodeInfo_Location): Uint8Array;
            toProtoMsg(message: _19.SourceCodeInfo_Location): _19.SourceCodeInfo_LocationProtoMsg;
        };
        GeneratedCodeInfo: {
            typeUrl: string;
            encode(message: _19.GeneratedCodeInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _19.GeneratedCodeInfo;
            fromJSON(object: any): _19.GeneratedCodeInfo;
            toJSON(message: _19.GeneratedCodeInfo): unknown;
            fromPartial(object: Partial<_19.GeneratedCodeInfo>): _19.GeneratedCodeInfo;
            fromAmino(object: _19.GeneratedCodeInfoAmino): _19.GeneratedCodeInfo;
            toAmino(message: _19.GeneratedCodeInfo): _19.GeneratedCodeInfoAmino;
            fromAminoMsg(object: _19.GeneratedCodeInfoAminoMsg): _19.GeneratedCodeInfo;
            fromProtoMsg(message: _19.GeneratedCodeInfoProtoMsg): _19.GeneratedCodeInfo;
            toProto(message: _19.GeneratedCodeInfo): Uint8Array;
            toProtoMsg(message: _19.GeneratedCodeInfo): _19.GeneratedCodeInfoProtoMsg;
        };
        GeneratedCodeInfo_Annotation: {
            typeUrl: string;
            encode(message: _19.GeneratedCodeInfo_Annotation, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _19.GeneratedCodeInfo_Annotation;
            fromJSON(object: any): _19.GeneratedCodeInfo_Annotation;
            toJSON(message: _19.GeneratedCodeInfo_Annotation): unknown;
            fromPartial(object: Partial<_19.GeneratedCodeInfo_Annotation>): _19.GeneratedCodeInfo_Annotation;
            fromAmino(object: _19.GeneratedCodeInfo_AnnotationAmino): _19.GeneratedCodeInfo_Annotation;
            toAmino(message: _19.GeneratedCodeInfo_Annotation): _19.GeneratedCodeInfo_AnnotationAmino;
            fromAminoMsg(object: _19.GeneratedCodeInfo_AnnotationAminoMsg): _19.GeneratedCodeInfo_Annotation;
            fromProtoMsg(message: _19.GeneratedCodeInfo_AnnotationProtoMsg): _19.GeneratedCodeInfo_Annotation;
            toProto(message: _19.GeneratedCodeInfo_Annotation): Uint8Array;
            toProtoMsg(message: _19.GeneratedCodeInfo_Annotation): _19.GeneratedCodeInfo_AnnotationProtoMsg;
        };
        Any: {
            typeUrl: string;
            encode(message: _18.Any, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _18.Any;
            fromJSON(object: any): _18.Any;
            toJSON(message: _18.Any): unknown;
            fromPartial(object: Partial<_18.Any>): _18.Any;
            fromAmino(object: _18.AnyAmino): _18.Any;
            toAmino(message: _18.Any): _18.AnyAmino;
            fromAminoMsg(object: _18.AnyAminoMsg): _18.Any;
            fromProtoMsg(message: _18.AnyProtoMsg): _18.Any;
            toProto(message: _18.Any): Uint8Array;
            toProtoMsg(message: _18.Any): _18.AnyProtoMsg;
        };
    };
}
